//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: tensorflow/core/framework/resource_handle.proto
namespace tensorflow
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ResourceHandle")]
  public partial class ResourceHandle : global::ProtoBuf.IExtensible
  {
    public ResourceHandle() {}
    
    private string _device = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"device", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string device
    {
      get { return _device; }
      set { _device = value; }
    }
    private string _container = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"container", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string container
    {
      get { return _container; }
      set { _container = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private ulong _hash_code = default(ulong);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hash_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(ulong))]
    public ulong hash_code
    {
      get { return _hash_code; }
      set { _hash_code = value; }
    }
    private string _maybe_type_name = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"maybe_type_name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string maybe_type_name
    {
      get { return _maybe_type_name; }
      set { _maybe_type_name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: tensorflow/core/framework/tensor.proto
// Note: requires additional types generated from: tensorflow/core/framework/resource_handle.proto
// Note: requires additional types generated from: tensorflow/core/framework/tensor_shape.proto
// Note: requires additional types generated from: tensorflow/core/framework/types.proto
namespace tensorflow
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TensorProto")]
  public partial class TensorProto : global::ProtoBuf.IExtensible
  {
    public TensorProto() {}
    
    private tensorflow.DataType _dtype = tensorflow.DataType.DT_INVALID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"dtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(tensorflow.DataType.DT_INVALID)]
    public tensorflow.DataType dtype
    {
      get { return _dtype; }
      set { _dtype = value; }
    }
    private tensorflow.TensorShapeProto _tensor_shape = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"tensor_shape", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tensorflow.TensorShapeProto tensor_shape
    {
      get { return _tensor_shape; }
      set { _tensor_shape = value; }
    }
    private int _version_number = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"version_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int version_number
    {
      get { return _version_number; }
      set { _version_number = value; }
    }
    private byte[] _tensor_content = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"tensor_content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] tensor_content
    {
      get { return _tensor_content; }
      set { _tensor_content = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _half_val = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(13, Name=@"half_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> half_val
    {
      get { return _half_val; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _float_val = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(5, Name=@"float_val", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<float> float_val
    {
      get { return _float_val; }
    }
  
    private readonly global::System.Collections.Generic.List<double> _double_val = new global::System.Collections.Generic.List<double>();
    [global::ProtoBuf.ProtoMember(6, Name=@"double_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<double> double_val
    {
      get { return _double_val; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _int_val = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"int_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<int> int_val
    {
      get { return _int_val; }
    }
  
    private readonly global::System.Collections.Generic.List<byte[]> _string_val = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(8, Name=@"string_val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> string_val
    {
      get { return _string_val; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _scomplex_val = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(9, Name=@"scomplex_val", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<float> scomplex_val
    {
      get { return _scomplex_val; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _int64_val = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(10, Name=@"int64_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> int64_val
    {
      get { return _int64_val; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _bool_val = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(11, Name=@"bool_val", DataFormat = global::ProtoBuf.DataFormat.Default, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<bool> bool_val
    {
      get { return _bool_val; }
    }
  
    private readonly global::System.Collections.Generic.List<double> _dcomplex_val = new global::System.Collections.Generic.List<double>();
    [global::ProtoBuf.ProtoMember(12, Name=@"dcomplex_val", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<double> dcomplex_val
    {
      get { return _dcomplex_val; }
    }
  
    private readonly global::System.Collections.Generic.List<tensorflow.ResourceHandle> _resource_handle_val = new global::System.Collections.Generic.List<tensorflow.ResourceHandle>();
    [global::ProtoBuf.ProtoMember(14, Name=@"resource_handle_val", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tensorflow.ResourceHandle> resource_handle_val
    {
      get { return _resource_handle_val; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: tensorflow/core/framework/tensor_shape.proto
namespace tensorflow
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TensorShapeProto")]
  public partial class TensorShapeProto : global::ProtoBuf.IExtensible
  {
    public TensorShapeProto() {}
    
    private readonly global::System.Collections.Generic.List<tensorflow.TensorShapeProto.Dim> _dim = new global::System.Collections.Generic.List<tensorflow.TensorShapeProto.Dim>();
    [global::ProtoBuf.ProtoMember(2, Name=@"dim", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tensorflow.TensorShapeProto.Dim> dim
    {
      get { return _dim; }
    }
  
    private bool _unknown_rank = default(bool);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"unknown_rank", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool unknown_rank
    {
      get { return _unknown_rank; }
      set { _unknown_rank = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Dim")]
  public partial class Dim : global::ProtoBuf.IExtensible
  {
    public Dim() {}
    
    private long _size = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"size", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long size
    {
      get { return _size; }
      set { _size = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: tensorflow/core/framework/op_def.proto
// Note: requires additional types generated from: tensorflow/core/framework/attr_value.proto
// Note: requires additional types generated from: tensorflow/core/framework/types.proto
namespace tensorflow
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpDef")]
  public partial class OpDef : global::ProtoBuf.IExtensible
  {
    public OpDef() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<tensorflow.OpDef.ArgDef> _input_arg = new global::System.Collections.Generic.List<tensorflow.OpDef.ArgDef>();
    [global::ProtoBuf.ProtoMember(2, Name=@"input_arg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tensorflow.OpDef.ArgDef> input_arg
    {
      get { return _input_arg; }
    }
  
    private readonly global::System.Collections.Generic.List<tensorflow.OpDef.ArgDef> _output_arg = new global::System.Collections.Generic.List<tensorflow.OpDef.ArgDef>();
    [global::ProtoBuf.ProtoMember(3, Name=@"output_arg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tensorflow.OpDef.ArgDef> output_arg
    {
      get { return _output_arg; }
    }
  
    private readonly global::System.Collections.Generic.List<tensorflow.OpDef.AttrDef> _attr = new global::System.Collections.Generic.List<tensorflow.OpDef.AttrDef>();
    [global::ProtoBuf.ProtoMember(4, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tensorflow.OpDef.AttrDef> attr
    {
      get { return _attr; }
    }
  
    private tensorflow.OpDeprecation _deprecation = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"deprecation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tensorflow.OpDeprecation deprecation
    {
      get { return _deprecation; }
      set { _deprecation = value; }
    }
    private string _summary = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"summary", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string summary
    {
      get { return _summary; }
      set { _summary = value; }
    }
    private string _description = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private bool _is_commutative = default(bool);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"is_commutative", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_commutative
    {
      get { return _is_commutative; }
      set { _is_commutative = value; }
    }
    private bool _is_aggregate = default(bool);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"is_aggregate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_aggregate
    {
      get { return _is_aggregate; }
      set { _is_aggregate = value; }
    }
    private bool _is_stateful = default(bool);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"is_stateful", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_stateful
    {
      get { return _is_stateful; }
      set { _is_stateful = value; }
    }
    private bool _allows_uninitialized_input = default(bool);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"allows_uninitialized_input", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool allows_uninitialized_input
    {
      get { return _allows_uninitialized_input; }
      set { _allows_uninitialized_input = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ArgDef")]
  public partial class ArgDef : global::ProtoBuf.IExtensible
  {
    public ArgDef() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _description = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private tensorflow.DataType _type = tensorflow.DataType.DT_INVALID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(tensorflow.DataType.DT_INVALID)]
    public tensorflow.DataType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _type_attr = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"type_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type_attr
    {
      get { return _type_attr; }
      set { _type_attr = value; }
    }
    private string _number_attr = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"number_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string number_attr
    {
      get { return _number_attr; }
      set { _number_attr = value; }
    }
    private string _type_list_attr = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"type_list_attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type_list_attr
    {
      get { return _type_list_attr; }
      set { _type_list_attr = value; }
    }
    private bool _is_ref = default(bool);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"is_ref", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool is_ref
    {
      get { return _is_ref; }
      set { _is_ref = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttrDef")]
  public partial class AttrDef : global::ProtoBuf.IExtensible
  {
    public AttrDef() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _type = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private tensorflow.AttrValue _default_value = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"default_value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tensorflow.AttrValue default_value
    {
      get { return _default_value; }
      set { _default_value = value; }
    }
    private string _description = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"description", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string description
    {
      get { return _description; }
      set { _description = value; }
    }
    private bool _has_minimum = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"has_minimum", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool has_minimum
    {
      get { return _has_minimum; }
      set { _has_minimum = value; }
    }
    private long _minimum = default(long);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"minimum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long minimum
    {
      get { return _minimum; }
      set { _minimum = value; }
    }
    private tensorflow.AttrValue _allowed_values = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"allowed_values", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tensorflow.AttrValue allowed_values
    {
      get { return _allowed_values; }
      set { _allowed_values = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpDeprecation")]
  public partial class OpDeprecation : global::ProtoBuf.IExtensible
  {
    public OpDeprecation() {}
    
    private int _version = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _explanation = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"explanation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string explanation
    {
      get { return _explanation; }
      set { _explanation = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OpList")]
  public partial class OpList : global::ProtoBuf.IExtensible
  {
    public OpList() {}
    
    private readonly global::System.Collections.Generic.List<tensorflow.OpDef> _op = new global::System.Collections.Generic.List<tensorflow.OpDef>();
    [global::ProtoBuf.ProtoMember(1, Name=@"op", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tensorflow.OpDef> op
    {
      get { return _op; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}
// Generated from: tensorflow/core/framework/types.proto
namespace tensorflow
{
    [global::ProtoBuf.ProtoContract(Name=@"DataType")]
    public enum DataType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_INVALID", Value=0)]
      DT_INVALID = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_FLOAT", Value=1)]
      DT_FLOAT = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_DOUBLE", Value=2)]
      DT_DOUBLE = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_INT32", Value=3)]
      DT_INT32 = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_UINT8", Value=4)]
      DT_UINT8 = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_INT16", Value=5)]
      DT_INT16 = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_INT8", Value=6)]
      DT_INT8 = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_STRING", Value=7)]
      DT_STRING = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_COMPLEX64", Value=8)]
      DT_COMPLEX64 = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_INT64", Value=9)]
      DT_INT64 = 9,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_BOOL", Value=10)]
      DT_BOOL = 10,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_QINT8", Value=11)]
      DT_QINT8 = 11,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_QUINT8", Value=12)]
      DT_QUINT8 = 12,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_QINT32", Value=13)]
      DT_QINT32 = 13,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_BFLOAT16", Value=14)]
      DT_BFLOAT16 = 14,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_QINT16", Value=15)]
      DT_QINT16 = 15,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_QUINT16", Value=16)]
      DT_QUINT16 = 16,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_UINT16", Value=17)]
      DT_UINT16 = 17,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_COMPLEX128", Value=18)]
      DT_COMPLEX128 = 18,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_HALF", Value=19)]
      DT_HALF = 19,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_RESOURCE", Value=20)]
      DT_RESOURCE = 20,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_FLOAT_REF", Value=101)]
      DT_FLOAT_REF = 101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_DOUBLE_REF", Value=102)]
      DT_DOUBLE_REF = 102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_INT32_REF", Value=103)]
      DT_INT32_REF = 103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_UINT8_REF", Value=104)]
      DT_UINT8_REF = 104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_INT16_REF", Value=105)]
      DT_INT16_REF = 105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_INT8_REF", Value=106)]
      DT_INT8_REF = 106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_STRING_REF", Value=107)]
      DT_STRING_REF = 107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_COMPLEX64_REF", Value=108)]
      DT_COMPLEX64_REF = 108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_INT64_REF", Value=109)]
      DT_INT64_REF = 109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_BOOL_REF", Value=110)]
      DT_BOOL_REF = 110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_QINT8_REF", Value=111)]
      DT_QINT8_REF = 111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_QUINT8_REF", Value=112)]
      DT_QUINT8_REF = 112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_QINT32_REF", Value=113)]
      DT_QINT32_REF = 113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_BFLOAT16_REF", Value=114)]
      DT_BFLOAT16_REF = 114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_QINT16_REF", Value=115)]
      DT_QINT16_REF = 115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_QUINT16_REF", Value=116)]
      DT_QUINT16_REF = 116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_UINT16_REF", Value=117)]
      DT_UINT16_REF = 117,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_COMPLEX128_REF", Value=118)]
      DT_COMPLEX128_REF = 118,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_HALF_REF", Value=119)]
      DT_HALF_REF = 119,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DT_RESOURCE_REF", Value=120)]
      DT_RESOURCE_REF = 120
    }
  
}
// Generated from: tensorflow/core/framework/attr_value.proto
// Note: requires additional types generated from: tensorflow/core/framework/tensor.proto
// Note: requires additional types generated from: tensorflow/core/framework/tensor_shape.proto
// Note: requires additional types generated from: tensorflow/core/framework/types.proto
namespace tensorflow
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttrValue")]
  public partial class AttrValue : global::ProtoBuf.IExtensible
  {
    public AttrValue() {}
    
    private byte[] _s = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"s", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] s
    {
      get { return _s; }
      set { _s = value; }
    }
    private long _i = default(long);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"i", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long i
    {
      get { return _i; }
      set { _i = value; }
    }
    private float _f = default(float);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"f", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    [global::System.ComponentModel.DefaultValue(default(float))]
    public float f
    {
      get { return _f; }
      set { _f = value; }
    }
    private bool _b = default(bool);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool b
    {
      get { return _b; }
      set { _b = value; }
    }
    private tensorflow.DataType _type = tensorflow.DataType.DT_INVALID;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(tensorflow.DataType.DT_INVALID)]
    public tensorflow.DataType type
    {
      get { return _type; }
      set { _type = value; }
    }
    private tensorflow.TensorShapeProto _shape = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"shape", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tensorflow.TensorShapeProto shape
    {
      get { return _shape; }
      set { _shape = value; }
    }
    private tensorflow.TensorProto _tensor = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"tensor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tensorflow.TensorProto tensor
    {
      get { return _tensor; }
      set { _tensor = value; }
    }
    private tensorflow.AttrValue.ListValue _list = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tensorflow.AttrValue.ListValue list
    {
      get { return _list; }
      set { _list = value; }
    }
    private tensorflow.NameAttrList _func = null;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"func", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tensorflow.NameAttrList func
    {
      get { return _func; }
      set { _func = value; }
    }
    private string _placeholder = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"placeholder", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string placeholder
    {
      get { return _placeholder; }
      set { _placeholder = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ListValue")]
  public partial class ListValue : global::ProtoBuf.IExtensible
  {
    public ListValue() {}
    
    private readonly global::System.Collections.Generic.List<byte[]> _s = new global::System.Collections.Generic.List<byte[]>();
    [global::ProtoBuf.ProtoMember(2, Name=@"s", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<byte[]> s
    {
      get { return _s; }
    }
  
    private readonly global::System.Collections.Generic.List<long> _i = new global::System.Collections.Generic.List<long>();
    [global::ProtoBuf.ProtoMember(3, Name=@"i", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<long> i
    {
      get { return _i; }
    }
  
    private readonly global::System.Collections.Generic.List<float> _f = new global::System.Collections.Generic.List<float>();
    [global::ProtoBuf.ProtoMember(4, Name=@"f", DataFormat = global::ProtoBuf.DataFormat.FixedSize, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<float> f
    {
      get { return _f; }
    }
  
    private readonly global::System.Collections.Generic.List<bool> _b = new global::System.Collections.Generic.List<bool>();
    [global::ProtoBuf.ProtoMember(5, Name=@"b", DataFormat = global::ProtoBuf.DataFormat.Default, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<bool> b
    {
      get { return _b; }
    }
  
    private readonly global::System.Collections.Generic.List<tensorflow.DataType> _type = new global::System.Collections.Generic.List<tensorflow.DataType>();
    [global::ProtoBuf.ProtoMember(6, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement, Options = global::ProtoBuf.MemberSerializationOptions.Packed)]
    public global::System.Collections.Generic.List<tensorflow.DataType> type
    {
      get { return _type; }
    }
  
    private readonly global::System.Collections.Generic.List<tensorflow.TensorShapeProto> _shape = new global::System.Collections.Generic.List<tensorflow.TensorShapeProto>();
    [global::ProtoBuf.ProtoMember(7, Name=@"shape", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tensorflow.TensorShapeProto> shape
    {
      get { return _shape; }
    }
  
    private readonly global::System.Collections.Generic.List<tensorflow.TensorProto> _tensor = new global::System.Collections.Generic.List<tensorflow.TensorProto>();
    [global::ProtoBuf.ProtoMember(8, Name=@"tensor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tensorflow.TensorProto> tensor
    {
      get { return _tensor; }
    }
  
    private readonly global::System.Collections.Generic.List<tensorflow.NameAttrList> _func = new global::System.Collections.Generic.List<tensorflow.NameAttrList>();
    [global::ProtoBuf.ProtoMember(9, Name=@"func", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tensorflow.NameAttrList> func
    {
      get { return _func; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NameAttrList")]
  public partial class NameAttrList : global::ProtoBuf.IExtensible
  {
    public NameAttrList() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private readonly global::System.Collections.Generic.List<tensorflow.NameAttrList.AttrEntry> _attr = new global::System.Collections.Generic.List<tensorflow.NameAttrList.AttrEntry>();
    [global::ProtoBuf.ProtoMember(2, Name=@"attr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<tensorflow.NameAttrList.AttrEntry> attr
    {
      get { return _attr; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AttrEntry")]
  public partial class AttrEntry : global::ProtoBuf.IExtensible
  {
    public AttrEntry() {}
    
    private string _key = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private tensorflow.AttrValue _value = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public tensorflow.AttrValue value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}